### ISSUE TITLE
Versioning inconsistency: v6.0.0 on CircleCI Developer Hub, v5.1.0 on GitHub

### ISSUE THREAD

**Issue by davidjb** [CircleCI-Public/aws-sam-serverless-orb#70]
## Orb version:

Unsure - probably either 6.0.0 or 5.1.0

## What happened:

The version for this orb on https://circleci.com/developer/orbs/orb/circleci/aws-sam-serverless is v6.0.0 but the releases here on GitHub are at latest v5.1.0 (https://github.com/CircleCI-Public/aws-sam-serverless-orb/releases). 

Trying to use `circleci/aws-sam-serverless@5.1` in my CI config errors with:

> `Cannot find circleci/aws-sam-serverless@5.1 in the orb registry. Check that the namespace, orb name and version are correct.`

Using version 6.0 in my config works fine, though I'm not sure what this version incorporates and whether it contains the fix in v5.1.0.

## Expected behavior:

Versions should be consistent and clear as to which to use.

**Comment by brivu** [comment]
Hey @davidjb - The correct version should be version 6.0. I've added the message below to the release. 

We apologize for any confusion caused by the recent release labeled as a major update. This was an unintentional oversight, and we recognize the importance of clarity in versioning.
Upon further review, it has been identified that the changes introduced primarily revolve around deprecating certain images rather than significant feature enhancements. Although this is a major release, it should be treated as a patch.

**Comment by davidjb** [comment]
Thanks for clarifying @brivu. Given the changeset https://github.com/CircleCI-Public/aws-sam-serverless-orb/compare/v5.0.0...v6.0.0 involves what could be considered a backwards-incompatible change (i.e. changing default behaviour and image), a major version bump appears warranted.
